site_name: PurpleClay Docs
site_description: Home for all of the PurpleClay project documentation
site_url: https://docs.purpleclay.dev/
copyright: Always thinking. Forever learning. 💡
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    primary: deep purple
    accent: purple
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/purpleclay
      name: Purple Clay on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/purpleclaydev
      name: Purple Clay on Twitter
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/purpleclay
      name: Purple Clay on Docker Hub

plugins:
  - minify:
      minify_html: true
